### ISSUE TITLE
wow this is amazing

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#1]
Hi, this is pretty amazing

your on a roll first selected.el and now this ;-). 
im playing with it and it works great so far, ill report if i find any buys

again like with selected.el i highly recommend you try and UL to melpa so it gets much more exposure :)

thx again

Z

**Comment by Kungsgeten** [comment]
It has been uploaded to MELPA and hopefully it will be available soon. It took some time due to me being a git n00b.
