### ISSUE TITLE
org-element-lineage is only in org-mode version 8.3+

### ISSUE THREAD

**Issue by jpkotta** [Kungsgeten/yankpad#10]
The current stable version of Emacs (24.5) comes with org-mode 8.2.10, which doesn't have org-element-lineage.  I'm not sure if there are other problems, this is the first one that pops up though.

**Comment by Kungsgeten** [comment]
Thank you for reporting this! Should be fixed now. 3216213b19afb42c35c527ecf5ca266b2bfc0d00
