### ISSUE TITLE
pasting orgmode headers into an org buffer, respect org header level (like in org-paste-subtree)

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#12]
Hi again

so after using yankpad daily over the last few months i think my most wanted feature now is respecting org header levels when pasting a org snippet :)
for example if i have a snipper that  has headers like this
`* item 1
** item 1.1
`

and i insetert the snippet under a header with 3 starts (level 3) ie `***` i would like yasnippet to paste the items as

`**** item 1
***** item 1.1
`

does that make sense? i know (and use) the command  org-paste-subtree that does exactly that (modify the level of the subtree to make sure the tree fits in nicely at the yank position). can we somehow implement that into yankpas if in an org file?

thx!

Z

**Comment by Kungsgeten** [comment]
Good idea! I've now added it as an optional variable `yankpad-respect-current-org-level`, which is true by default.
