### ISSUE TITLE
Yankpad broken for buffer when not choosing category

### ISSUE THREAD

**Issue by novoid** [Kungsgeten/yankpad#14]
Hi!

yankpad does not seem to automatically assign the "org-mode" category when I am within an Org-mode buffer. But I am not sure if I did not understand the category feature completely. However, this is not the issue I want to report here. It's just a remark.

When I invoke yankpad-insert and do (accidentally) not choose any mode manually (I have to because the mode is not recognized automatically - see remark above) but press Enter right away, the current buffer can not use yankpad any more because yankpad-insert does not provide any possible target to insert.

**Comment by Kungsgeten** [comment]
Regarding the first issue: Yankpad has to be loaded before you open the file and one of your categories has to be named `org-mode`.

Second issue: I did not know that it was possible to choose "no category" by accident. I'm not sure what to do about that. Once you've set a category for a buffer `yankpad-insert` will continue to use that category. That seems to be the case here: you've chosen a (non-existent?) category which doesn't contain any entries. To switch category, use `M-x yankpad-set-category`. That should solve your problem.

**Comment by novoid** [comment]
Hi Kungsgeten,

I'll have to look into the order of loading things because yankpad as well as my org-mode files are loaded at startup.

Yes, I did come to the same reasoning: yankpad fell into a category with no entries. Thanks for the pointer to `yankpad-set-category` to get our of this situation. However, I was thinking of preventing the situation in the first place by making sure that an existing category is chosen when asking for a category.

**Comment by Kungsgeten** [comment]
Hi!

I've just uploaded a new version, please try it out and see if it fixes your problem. I think it should ask for the category again, if you do not have any set.

**Comment by novoid** [comment]
My Melpa still has `20160716.1613`. What is your Melpa-update policy? Or do I have to switch from Melpa package to git repository?

**Comment by Kungsgeten** [comment]
There should be no need to switch. The version shown at https://melpa.org/#/yankpad is 20160903.1935. Packages aren't upgraded automatically though. Use `M-x package-list-packages` and press `U x` to upgrade all packages. I think `M-x package-reinstall yankpad` should work too, but I haven't tried it.

**Comment by novoid** [comment]
I'm using `(add-to-list 'package-archives '("melpa" . "http://stable.melpa.org/packages/"))` and after `package-list-packages` (and optional `r`) the yankpad version in the list stays at `20160716.1613`. When trying to upgrade via `U x` the yankpad still does not get updated.

Is it because I am using `stable` and you are referring to something different?

**Comment by Kungsgeten** [comment]
Yes, its because you're using stable. I haven't made any stable release (and actually do not know how to).

**Comment by Kungsgeten** [comment]
Sorry for taking so long, but I've tagged the latest version as stable (I have been using it without problems, and haven't heard anything from other users). It should hopefully appear on Melpa stable soon.
