### ISSUE TITLE
[enhancement] Function to reload file

### ISSUE THREAD

**Issue by ag91** [Kungsgeten/yankpad#16]
Hello,

thanks for this software! It made me start using snippets more and has significantly simplified my life.

I was trying to reload the snippets after editing my file, and I discovered there is not a direct function to do it. I resorted to use src_elisp{(yankpad-set-active-snippets)}. Would it be meaningful to have this as a function: like yankpad-reload?
Thanks again!

**Comment by Kungsgeten** [comment]
Hi! I'm glad you enjoy it!

Yes its a good idea, since its quite common wanting to reload your file after editing it. I've added a `yankpad-reload` now (just had to rename a function and make it interactive).
