### ISSUE TITLE
level 2 for categories , level 3 for snippets

### ISSUE THREAD

**Issue by gregnwosu** [Kungsgeten/yankpad#22]
Its purely aesthetic but i think it would be nice for yankpad.org to have one root instead of many

**Comment by Kungsgeten** [comment]
It was quite a long time since I implemented it, and I haven't used it myself, but see #4 I think what you suggest is possible, with something like:
```
(setq yankpad-category-heading-level 2)
(setq yankpad-snippet-heading-level 3)
```

**Comment by Kungsgeten** [comment]
I'm marking this as closed, since I believe the functionality is there. If you meant something else with the issue, please feel free to reopen it.
