### ISSUE TITLE
certain keyword doesn't work for expand

### ISSUE THREAD

**Issue by showgood** [Kungsgeten/yankpad#23]
for example:

* source blocks
** <l: elisp
#+begin_src elisp
$0
#+end_src

in this case, type <l and invoke yankpad-expand doesn't work.

**Comment by Kungsgeten** [comment]
`yankpad-expand` used `word-at-point` to get the keyword you just wrote. I have now changed it to `symbol-at-point` instead. I think that will work in your case (at least in `org-mode`).
