### ISSUE TITLE
Adding code snippets in SRC blocks

### ISSUE THREAD

**Issue by alastairdb** [Kungsgeten/yankpad#25]
I noticed that yankpad parses snippets as org syntax. If you use the snippets outside of org files, such as in files for program code, this can cause problems. In particular, Python comments get parsed as org comments, and, when they are inserted into a file, the resulting indentation is confused. It seems to me that snippets for program code should be left verbatim (modulo yasnippet rewriting). 

To achieve that end, I tried adding a new tag `rawsrc` to snippets, which lets you write your code in `begin_src`, `end_src` blocks and strips out these lines when the snippet is inserted. I needed the following change to `yankpad--run-snippet`:

``` elisp
@@ -262,11 +262,15 @@ Return the result of the function output as a string."
                                'auto)
                               ((and (require 'yasnippet nil t) yas-minor-mode)
                                yas-indent-line)
-                              (t t))))
+                              (t t)))
+		(rawsrc (member "rawsrc" tags)))
             (when (and yankpad-respect-current-org-level
                        (equal major-mode 'org-mode)
                        (org-current-level))
               (setq prepend-asterisks (org-current-level)))
+	    (when rawsrc
+	      (setf (car content) (replace-regexp-in-string "^#\\+BEGIN_SRC.*\n" "" (car content)))
+	      (setf (car content) (replace-regexp-in-string "^#\\+END_SRC.*$" "" (car content))))
             (yankpad--insert-snippet-text
              (replace-regexp-in-string
               "^\\\\[*]" (make-string prepend-asterisks ?*) (car content))
```
I am not sure if this is the best solution, but I think using src blocks is the way to go.

**Comment by Kungsgeten** [comment]
Hmm, I already thought they were added verbatim :) Could you please give an example of a snippet which doesn't work as it should, and a context in which you try to expand it? That way it'll be easier to understand the problem.

**Comment by alastairdb** [comment]
Here is an example:
``` Org
* python-mode
** Plumbum                                     :indent_fixed:
from plumbum import cli

class ${1:MyApp}(cli.Application):

    # verbosity_level = cli.CountOf("-v")

    def main(self, filename):
        pass

if __name__ == "__main__":
    $1.run()

```
Which gets inserted into my Python file as:

``` python
from plumbum import cli

class MyApp(cli.Application):

# verbosity_level = cli.CountOf("-v")

def main(self, filename):
    pass

if __name__ == "__main__":
    MyApp.run()

```

The comment and the `main` method are indented incorrectly. 

Of course, I could have wrapped that code with `begin_src` and `end_src` lines. But then I would have to delete those two lines in the Python file. My diff just automates that process.

**Comment by Kungsgeten** [comment]
For me it works if you remove the `:indent_fixed:` tag. You are correct though that it seems that the comment line really isn't interpreted as such. I'll see if I can fix this somehow. In any way it is probably a nice feature being able to use source blocks to write snippets, in case you want to write the snippets in the native code mode.

**Comment by alastairdb** [comment]
Ah yes, it works for me, too. I thought I had tried every variant of the indent tag, but, I guess, I missed one.

As you indicate, the other reasons for using the src blocks are the syntax highlighting, the ability to edit natively with `org-edit-src-code` and the fact that the snippet is actually source code.

**Comment by Kungsgeten** [comment]
The latest commit ensures that the text in snippets is "verbatim", so `org-mode` does nothing with the text inside the snippets. I've also added the `:src:` tag, which will concatenate the contents of all source blocks inside a snippet (and discard the rest of the text). I think it is a nice addition, thanks!
