### ISSUE TITLE
yankpad-map direct bind?

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#29]
Hi again!

so as you can see im doing my yankpad spring cleaning so more question, hope you dont mind :)

follwowing your great advice with issue #28 , i started using yankpad-map. 

for several reasons i would like to use them via hydras. so i stated playing around with trying to get a function for each yankpad-map and came up with something like this (spoilers: i cant code :))):

```
(defun zzzzxxxx ()
" insert yankpad o  "
(interactive)
(yankpad-map "o")
)
```

now this clearly dosent work since i dont know how to instruct emacs to press/enter 'o' after i launch the `yankpad-map` via the function.

any tips on how to do so? 

thx!

Z

**Comment by Kungsgeten** [comment]
It seems like #32 may be of interest to you, since that adds hydra-like functionality to `yankpad-map`. If you want to do what you describe, you could use something like this:

```
(defun zzzzxxxx ()
  " insert yankpad o  "
  (interactive)
  (setq unread-command-events (listify-key-sequence (kbd "o")))
  (yankpad-map))
```

**Comment by Kungsgeten** [comment]
You can now use `yankpad-map-simulate` for this.
