### ISSUE TITLE
support multi keys yankpad-map

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#30]
Hi

would it possible to add support for multi key yankpad-map keys?

so something like this:

```
* img: image size  X                                                 :key:ix: 
* img: image size  Y                                                  :key:iy: 
```
this (for me at least) could improve on usability 

best

Z

**Comment by Kungsgeten** [comment]
This already works for me. Have you tried it?

**Comment by zeltak** [comment]
yes that works, i did try it before unsuccessfully but probably mucked it somehow :)

thx, closing

Z
