### ISSUE TITLE
[Maybe a bug] yankpad-insert does not work on a org src block

### ISSUE THREAD

**Issue by ag91** [Kungsgeten/yankpad#34]
Hi,

Thanks very much for yankpad: a great interface over yasnippet!
I am using the latest version of it 20180324.949 and I may have found a bug.

I have an org file with the following org src block in it:

```
#+BEGIN_SRC org
,* bla
:PROPERTIES:
:CREATED:  [2018-03-27 Tue 13:30]
:END:

#+END_SRC
```
If I put the cursor into the block (or I use `C-c '` and I have the cursor in the newly opened buffer) and call yankpad-insert, it fails with

```
mapcar: Wrong type argument: integer-or-marker-p, nil
```

Using `debug-on-entry mapcar` I get:

```
Debugger entered--entering a function:
  apply(debug--implement-debug-on-entry (#[(ov) "\301\302\"\207" [ov overlay-get yas--snippet] 3] nil))
* mapcar(#[(ov) "\301\302\"\207" [ov overlay-get yas--snippet] 3] nil)
  yas-active-snippets(all)
  yas--check-commit-snippet()
  yas--post-command-handler()
```

Is something happening only on my system?  
I am running on Mac OS X with Emacs 25.1.2

P.S: I did not have chance to dive into the elisp yet, but I can give a look during the week if there is not an easy answer

**Comment by Kungsgeten** [comment]
Hi! It sounds like a bug, though I'm not sure if it is with `yankpad` or with `yasnippet`. I have no problem triggering snippets when the point/cursor is in a src-block. Does it fail directly after you use `M-x yankpad-insert`, or do you get to choose a snippet first? If so, what does that snippet look like? Do you have an active yankpad-category in the file?

**Comment by ag91** [comment]
Okay, after some experiments it seems that yankpad is okay. Removing this set (or better header :) of snippets:

```
* COMMENT latex-mode
** ar: latex arrow
\$$1 \xrightarrowx{$2} $3\$
** par: latex paragraph (nice for definitions)

\begin{paragraph}
{${1:Definition}}

{\addtolength{\leftskip}{2mm}

$0

}

\end{paragraph}
```
everything works normally again. I have the feeling that yasnippet syntax has changed slightly as these snippets were working fine earlier.

Thanks!
