### ISSUE TITLE
Symbol's function definition is void: prefix

### ISSUE THREAD

**Issue by arkhan** [Kungsgeten/yankpad#35]
Hello, I have this error:
```
Company backend ’company-yankpad’ could not be initialized:
Symbol’s function definition is void: prefix
```

**Comment by Kungsgeten** [comment]
Hi! I haven't implemented the `company` features of `yankpad` myself, but perhaps @sid-kurias knows the problem.

**Comment by sid-kurias** [comment]
sounds like company-mode is not installed. Is it installed?

**Comment by Kungsgeten** [comment]
I haven't heard anything about this since March. Marking this as closed for now.
