### ISSUE TITLE
trying to figure out yankpad-map-simulate with no sucess

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#36]
Hi!

im trying to use the new function `yankpad-map-simulate` with no success.

im sure its me doing something wrong but currently i tried this in my hydra

```
 ("r" (yankpad-map-simulate "pb")  "insert conf block" )
```
but this dosent seem to work for executing the snippet

```
*** pbash: paste with clipboard data                                 :key:pb:
#+BEGIN_SRC sh  :results none
$0
#+END_SRC
```

do i need to use `yankpad-map-press-pb` in the hydra?

sorry for being daft :)

best

Z

**Comment by zeltak** [comment]
perfect thx so much!

im very willing to contribute to the project (which i love so much) if toy can think of things a non programmer can contribution with :)

z

**Comment by Kungsgeten** [comment]
If you want to help it is always nice with articles (or blog posts) covering real world use cases (which isn't the case of the documentation) or screencasts. It would be interesting to read an article, or watch a screencast, about how you're using `yankpad` and what kind of problems it solves :)

**Comment by zeltak** [comment]
great i would be very happy to do a screencast. give me a few days and ill send it over

thx

Z

**Comment by zeltak** [comment]
Hi

Please find attached a link to download my screencast:

https://paste.xinu.at/AHVt/

please let me know how you find it, its my first try at screencasting -;)

im open to suggestions on how to improve it

also find here my org file used in the screencast

https://paste.xinu.at/lqz9f/

happy to help further in anyway!

best

Z
