### ISSUE TITLE
Run code (ie. kill line) before inserting the yankpad/yasnippet code

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#38]
Hi

im having issues with executing a yanpad snippet via yasnippet magic

for example take this code

```
*** bash.paste.line: paste with clipboard data                      :key:bpp:
`(kill-whole-line)` 
#+BEGIN_SRC sh  :results none
`(yank)` $0
#+END_SRC
```

here the actual kill takes place after the snippet has been executed. 

this is another example i tried
```
#+BEGIN_QUOTE
${0:`(if (region-active-p) (yas-selected-text) (yank))`}
#+END_QUOTE
```
which also worked not as expected 

is there anyway around this?

**Comment by Kungsgeten** [comment]
Not that I know of, no.

**Comment by Kungsgeten** [comment]
With the latest version there's a hook called `yanpad-before-snippet-hook`. Functions added to this hook can modify the snippet before it is inserted. The latest version also adds support for having properties in snippets (see the README). Here's an example of how we can define that having the property `LINE` in a snippet will replace the text `<line>` in the snippet with the current line:

```
(defun yp/replace-line (snippet)
  "If SNIPPET has a property named LINE the current line will be killed.
The text <line> in the snippet will then be replaced by the killed line."
  (when (assoc "LINE" (nth 4 snippet))
    (kill-whole-line)
    (setf (nth 3 snippet)
          (replace-regexp-in-string "<line>" (current-kill 0) (nth 3 snippet)))))

(add-hook 'yankpad-before-snippet-hook 'yp/replace-line)
```

You can then add a snippet like this to your Yankpad:

```
*** bash.paste.line: paste with clipboard data                      :props:key:bpp:
:PROPERTIES:
:LINE:
:END:
#+BEGIN_SRC sh  :results none
<line> $0
#+END_SRC
```
