### ISSUE TITLE
screencast

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#39]
Hi not sure you saw this in the closed issue so ill open an "issue"

Please find attached a link to download my screencast:

https://paste.xinu.at/AHVt/

please let me know how you find it, its my first try at screencasting -;)

im open to suggestions on how to improve it

also find here my org file used in the screencast

https://paste.xinu.at/lqz9f/

happy to help further in anyway!

best

Z

**Comment by Kungsgeten** [comment]
Nice examples! Are you going to upload it to Vimeo, YouTube or similar?

**Comment by zeltak** [comment]
thx!

i dont have a youtube account, do you mind downloading the cast and uploading it to your site/account?

if your to busy i can open an account in a few days

happy to help!

Z

**Comment by Kungsgeten** [comment]
Sorry for taking so long on getting back to you about this. I think it is best if you add it to your own account, since it is your video. I'll certainly link to it from the README when its out there :)

**Comment by zeltak** [comment]
Hi no worries:

ive started a youtube account and posted the video here:

https://youtu.be/xkkyE7d0Bpc

would be happy to help out in anything needed in the future!

best

Z
