### ISSUE TITLE
SUGGESTION: allow 3rd level to be snippets?

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#4]
Hi

im loving using yankpad after the complexity of yasnippet :) and also since im an orgmode fanboy this is great for me ;-)

one thing i notice while transitioning to yanpad from yasnippet is that i find myslef wanting sub levles in a category. for example in org mode i have > 50 snippets but some are for uni some for cooking some for home etc. 
will it be possible perhaps with a user defined option to make yankpad consider lv1 as category, igonre lv2 and use lv3 headers as snippets?

best

Z

**Comment by Kungsgeten** [comment]
Fair suggestion. I've made that configurable now. For now it is global though, so all snippets have to be at the same level (you can not have level 2 snippets in one category and level 3 snippets in another).

Add `(setq yankpad-snippet-heading-level 3)` to your init-file to try it out. You can also try to change `yankpad-category-heading-level` if you like.
