### ISSUE TITLE
Categorizing snippets in descriptive list

### ISSUE THREAD

**Issue by haqle** [Kungsgeten/yankpad#41]
Hi
As far as I know, only descriptive list items under the top level headings are considered snippets. I think it'd be great to be able to divide the descriptive list snippets into sub-categories. One way to achieve this is to define a new tag that tells yankpad to ignore headings and only look for descriptive list items.

**Comment by Kungsgeten** [comment]
Hi! I've commited a change to how descriptive list snippets work. If the descriptive list is in a "snippet" (a headline without any subheadings), then you need the `:snippetlist:` tag if you want to fetch snippets from it. If it is higher up in the hierarchy (not only top level, like before) you do not need that tag.

Thanks for the suggestion!
