### ISSUE TITLE
Unexpected yankpad-expand behavior

### ISSUE THREAD

**Issue by ndw** [Kungsgeten/yankpad#46]
Consider this fragment of my yankpad file:
```org
** Simple string replacements                                   :snippetlist:

   - wtf :: ¯\_(ツ)_/¯
```
The `yankpad-expand` replacement for `wtf` is "¯\\". Oddly, if I replace the first underscore with a "." or other character, it works fine. So for some reason backslash followed by underscore stops the expansion. Putting in an extra backslash doesn't help.

**Comment by Kungsgeten** [comment]
Thanks for reporting this! The problem had to do with the `org-element` API and how I used it. It seems to treat text followed by a backslash in some special way. I've commited a patch which seems to fix the issue.
