### ISSUE TITLE
Yankpad inserts extra newline

### ISSUE THREAD

**Issue by Wagk** [Kungsgeten/yankpad#47]
given an entry 
```
** bb: Bug                                                             :src:
#+BEGIN_SRC emacs-lisp
`(yas-with-comment "BUG: ")`$0
#+END_SRC
```
Inserting the snippet causes an extra newline to be inserted at the end of the snippet.

Is there a way to disable it? Or is it some misconfiguration on my side?

**Comment by Kungsgeten** [comment]
Hi! No it was a bug in the code, which I haven't reflected on before. I've fixed it now. Thanks for reporting this!
