### ISSUE TITLE
yankpad--remove-id-from-yankpad-capture assumes org-capture-last-stored-marker exists

### ISSUE THREAD

**Issue by MerlinsGreatBeard** [Kungsgeten/yankpad#48]
Backtrace:
----------------------------------------------------------------------------------------------------
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  org-entry-properties(#<marker in no buffer>)
  yankpad--remove-id-from-yankpad-capture()
  run-hooks(org-capture-after-finalize-hook)
  org-capture-finalize()
  org-capture-kill()
  funcall-interactively(org-capture-kill)
  call-interactively(org-capture-kill nil nil)
  command-execute(org-capture-kill)`

**Comment by Kungsgeten** [comment]
Thanks, I haven't encountered that problem. I think the latest commit should fix it.

**Comment by MerlinsGreatBeard** [comment]
Yes it works now, thanks!
