### ISSUE TITLE
Yankpad asks for a category although there is only one to choose from (in my setup)

### ISSUE THREAD

**Issue by novoid** [Kungsgeten/yankpad#55]
Hi,
I just have one single category (= topmost heading level) in my `yankpad.org` definition file. When I invoke `yankpad-expand`, I get asked to enter the category. In my setup, I just have to press `TAB`. However, this step is completely unnecessary from my perspective. If it is an easy change, I'd love to see this step omitted in this case.

Thanks!

**Comment by Kungsgeten** [comment]
Hi! It would be an easy change. I don't see any direct downside of this, so I'll see if I can change it. What you can do in the meantime is to set the variable `yankpad-default-category` to the name of your category. I think that should work.

**Comment by novoid** [comment]
I'm puzzled. I could have sworn that I've added the default category setting when upgrading to the most recent version of yankpad. I was wrong. It's now set but if this change is not much trouble, I do think that it's worth for many situations because I assume that this does not have negative side-effects.

**Comment by Kungsgeten** [comment]
I've changed the behavior to automatically choose the sole category if there's only one. Thanks for the suggestion!
