### ISSUE TITLE
yankpad-insert: (invalid-function (snippet (assoc name (yankpad-active-snippets))))

### ISSUE THREAD

**Issue by gambatte64** [Kungsgeten/yankpad#56]
Hello

eval of (yankpad-insert) yields an error (see below).
Thank you for your support.
Alfred

-------
Debugger entered--Lisp error: (invalid-function (snippet (assoc name (yankpad-active-snippets))))
  (snippet (assoc name (yankpad-active-snippets)))()
  yankpad-insert-from-current-category()
  yankpad-insert()
  eval((yankpad-insert) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

-------
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29

-------
yankpad is an installed package.

     Status: Installed in ‘yankpad-20200108.1811/’ (unsigned). Delete
    Version: 20200108.1811
     Commit: dd97994a8bff58e4d98aa6cb90aa08c5ddde5c82
    Summary: Paste snippets from an org-mode file
   Requires: emacs-25
   Homepage: http://github.com/Kungsgeten/yankpad
   Keywords: abbrev convenience 
Other versions: 20200108.1811 (melpa), 1.6 (melpa-stable).

-------
OS:
Windows 10 Professional

 Entered on [2020-01-12 Sun 18:43]

**Comment by Kungsgeten** [comment]
Hi! Thanks for the report!

I'm not sure what's wrong, but the line where the error occurs uses a macro found in `subr-x`. Could you please try and and eval the following, and then try again?

`(require 'subr-x)`

**Comment by gambatte64** [comment]
Hi!

Unfortunately it didn't help. The same error occurs.

Alfred

**Comment by gambatte64** [comment]
Hello,

fortunately (yankpad-insert) works now. Thank you!
Alfred
