### ISSUE TITLE
Yasnippet functions not working

### ISSUE THREAD

**Issue by sati-bodhi** [Kungsgeten/yankpad#59]
yasnippet functions don't seem to be working for me even though I have it installed already. 

```
* org-mode

** prose: insert prose                                                    :p:

#+BEGIN_PROSE
$0
#+END_PROSE
```
The above set up inserts `$0` literally without the tab stops.

**Comment by Kungsgeten** [comment]
You need to have `yas-minor-mode` enabled in the buffer. Otherwise `yankpad` won't use it.

**Comment by sati-bodhi** [comment]
Ok, issue's been resolved. Thank you.
