### ISSUE TITLE
[BUG] cant use lv3 snippets

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#6]
Hi
sorry for finding all these bugs, hope this isnt annoying :)
when i set:
```  (setq yankpad-snippet-heading-level 3)```
and then issue `yankpad-insert` the list comes up empty. if i change the level back to 2 then the 2nd level org heading do show.

any clue what to check to debug this?

**Comment by Kungsgeten** [comment]
I don't have the time to look into it right now, but I believe it may be because `yankpad-category-heading-level` has to be one step lower than `yankpad-snippet-heading-level`. I'll look into this.

**Comment by Kungsgeten** [comment]
I've pushed a fix to this to GitHub. Don't know how long it will take until its on Melpa.

**Comment by zeltak** [comment]
I can conforms this works thx  :)
