### ISSUE TITLE
"cons: Symbol’s function definition is void: string-trim" when using yankpad-insert

### ISSUE THREAD

**Issue by diovon** [Kungsgeten/yankpad#61]
I have set up yankpad today using emacs 26.3 on xubuntu 18.04 according to your readme.
since I'm a emacs beginner my complete init.el is:

```
(package-initialize)

(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(setq inhibit-startup-screen t)

(setq org-startup-indented t)

(setq-default calendar-week-start-day 1)

(toggle-frame-maximized)

(use-package yankpad
  :ensure t
  ;;:defer 10
  :init
  (setq yankpad-file "~/.emacs.d/yankpad.org")
  :config
  (bind-key "<f7>" 'yankpad-map)
  (bind-key "<f12>" 'yankpad-expand)
)
```

I used your example for my `yankpad.org`:
```
* Category 1

** Snippet title

    Here's a text snippet I want to insert.
```

After confirming yankpad-insert and snippet title I'll get the mentioned error message.

Can you tell me why this happens?

Thanks very much.

**Comment by novoid** [comment]
Hello @Kungsgeten,

I helped debugging this issue via remote session.

Fun fact: the initial error was `Symbol’s function definition is void: if-let`. This function got introduced with Emacs 25.1. `C-h f if-let` showed the help screen for `if-let` same as on my Emacs 26.3 except the ` in ‘subr-x.el’.` part of `if-let is a Lisp macro in ‘subr-x.el’.` As if there was no implementation to visit.

Just to play around with the issue, I sent him my implementation of that function. Then, the error changed to the mentioned `string-trim` which stuck even after removing the source of `if-let` from `init.el` again. Very strange to me.

I'm sure you do have a better understanding of what's happening here.

Thanks!

**Comment by Kungsgeten** [comment]
Hi! It may be something as simple as me forgetting to require `subr-x` (the file which defines the `string-trim` function, as well as `if-let` which @novoid mentioned). I've pushed a commit fixing that.

**Comment by diovon** [comment]
Thanks, will I get this fix over melpa too?

**Comment by diovon** [comment]
Wow, today I received the update via emacs package-list.
Now I didn't get the mentioned error and I can insert the snippets.

Thanks.

**Comment by diovon** [comment]
Fixed, Thanks.
