### ISSUE TITLE
Yankpad inserts table at level of Org heading instead of left margin as expected

### ISSUE THREAD

**Issue by TRSx80** [Kungsgeten/yankpad#63]
First, thanks for sharing this software, it's really useful! :beers: 

It is entirely possible that I am not understanding something here, but after searching around docs, variables, the Internet, Issues here, etc. I still cannot seem to figure this out.

Say I have a table like so in my yankpad.org file:
```
** table: plain 2Cx2R
|---+---|
|   |   |
|---+---|
|   |   |
|---+---|
```

If I try to yankpad that in under an Org heading, I end up with:
```
*** heading

    |---+---|
    |   |   |
    |---+---|
    |   |   |
    |---+---|
```
Whereas what I would expect would be:
```
*** heading

|---+---|
|   |   |
|---+---|
|   |   |
|---+---|
```
Is there some setting I can change, or...?  This is driving me nuts.  I used to indent everything to Org heading, but more recently I started writing everything aligned to left margin because I have some fairly deep level headings and I was running out of room.

I thought I could wrap it in some script to automate what I now do manually (removing spaces on left side), but then I thought to myself "that is crazy and there must be some setting you have overlooked" and then I decided to post here.

At one point I checked the default behavior of "C-c |" (`org-table-create-or-convert-from-region`) which did what I expect, aligning the table with the left margin.  I don't like how the top and bottom of the default tables are left open however, so that's not a solution for me, unfortunately.

I also thought changing the setting of `yankpad-respect-current-org-level` might help, but it did not (and I even did `yankpad-reload` afterward (not sure if necessary).

So, any hints would be greatly appreciated.  With the small amount of hair I have left to work with, I cannot afford to pull any more out... :smile:

**Comment by Kungsgeten** [comment]
Hi! I'm glad you enjoy Yankpad! Have you tried what's suggested under the `indent_nil` special tag in the README?

**Comment by TRSx80** [comment]
@Kungsgeten,

That worked!  Thank you so much for very fast reply!

I feel very foolish now, as it is right there in the README as you say.  :frowning_face:

I didn't realize all that useful information was so far down there, but now I will refer back to it much more often.  I think I only get so far into all the examples each time before reading a bunch of things that don't apply to me and bailing out.  But on each re-read I penetrate a little further...  It's a powerful tool though with lots of features (which is a Good Thing) so shame on me for not reading more before posting...

**Comment by Kungsgeten** [comment]
No worries at all! I think its quite hard (and sometimes cumbersome) to write documentation which is easy to follow and understand.

**Comment by TRSx80** [comment]
We were having very same discussion in another project that I am involved in.  Project lead referenced some book he had read, which made the point not to make people work too hard to find the information.  I think I must be on the spectrum somewhere (not suggesting you are, only speaking for myself), because this is something I have struggled with, personally, for years (when writing docs, or anything, really).  I have a tendency to ramble on and on...  So it is in the sense of "yes I have been there" that I offer up this hopefully constructive comment.

Perhaps move things around?  Move the examples down?  Or maybe not?  Maybe I am the only one who had problem finding this information.  I also been reading about format of eg., man pages and `--help` command line output, etc. for use in my own little tools recently.  So maybe I assume most important info at top and examples further down.

Also, I may have made another bad assumption.  There are so many little projects on GitHub with little to no documentation, that only provide examples and no real explanation.  So after reading through certain number of examples on the README, I think I gave up before getting to the information I was looking for.  I suppose I assumed that was the case here, but turned out not to be the case at all.  You actually have lots of really good and pertinent documentation, it's just way down there after the examples.

Anyway, my two cents.  Perhaps useful for your consideration as en educator.  Or perhaps I presume too much, and you could likely educate me volumes on the subject. :smile:  Anyway, nice chatting with you. :beers:
