### ISSUE TITLE
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 2) 4) org-get-heading(t t t t)

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/yankpad#64]
Just updated to latest org-mode, when triggering yankpad, getting following error:

```
> Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 2) 4)
>   org-get-heading(t t t t)
>   yankpad-snippets-at-point()
>   org-scan-tags(yankpad-snippets-at-point (lambda (todo tags-list level) (progn (setq org-cached-props nil) (or (and (= level 2))))) nil nil)
>   org-map-entries(yankpad-snippets-at-point "+LEVEL=2" tree)
>   yankpad--snippets("org")
>   yankpad-set-active-snippets()
>   yankpad-active-snippets()
>   yankpad-map()
>   funcall-interactively(yankpad-map)
>   call-interactively(yankpad-map nil nil)
>   command-execute(yankpad-map)
```

**Comment by Kungsgeten** [comment]
Which version of `org-mode` are you using (please try `M-x org-version`)? I just tried installing the latest version of `org-plus-contrib` and it works for me. `org-get-heading` takes four arguments, which is what the debugger seem to complain about.

**Comment by michaelsjackson** [comment]
It had N/A, I wrote there 9.3.6 I think, the latest known.  I took from the daily development package, so really the latest.

**Comment by michaelsjackson** [comment]
org-plus-contrib I installed once, it gave some errors, so removed that again, I did the manual installation.

**Comment by michaelsjackson** [comment]
For me org-get-heading shows this help information.

> org-get-heading is a compiled Lisp function in ‘org.el’.
> 
> (org-get-heading &optional NO-TAGS NO-TODO)
> 
> Return the heading of the current entry, without the stars.
> When NO-TAGS is non-nil, don’t include tags.
> When NO-TODO is non-nil, don’t include TODO keywords.
> 

`(defun org-get-heading (&optional no-tags no-todo)
  "Return the heading of the current entry, without the stars.
When NO-TAGS is non-nil, don't include tags.
When NO-TODO is non-nil, don't include TODO keywords."
  (save-excursion
    (org-back-to-heading t)
    (let ((case-fold-search nil))
      (cond
       ((and no-tags no-todo)
	(looking-at org-complex-heading-regexp)
	;; Return value has to be a string, but match group 4 is
	;; optional.
	(or (match-string 4) ""))
       (no-tags
	(looking-at (concat org-outline-regexp
			    "\\(.*?\\)"
			    "\\(?:[ \t]+:[[:alnum:]:_@#%]+:\\)?[ \t]*$"))
	(match-string 1))
       (no-todo
	(looking-at org-todo-line-regexp)
	(match-string 3))
       (t (looking-at org-heading-regexp)
	  (match-string 2))))))
`

**Comment by Kungsgeten** [comment]
Ok, then you do not have the same version as I do. Could you go to the definition of the function, then go to the top of the file (`org.el`) and check there if you really are using version 9.3.6?

**Comment by michaelsjackson** [comment]
Well, where can I check this, there is no version, it was showing originally, after installation N/A, which gave errors elsewhere, thus I wrote there some number, I took the latest, as my guessing is the daily builds should be even newer than that, I wrote 9.3.6.

For what should I grep in this file?  I looked around there is no version, or at least I do not know where and how to find it?

**Comment by Kungsgeten** [comment]
At the top of `org.el` I get see the following:

```
;; Carstens outline-mode for keeping track of everything.
;; Copyright (C) 2004-2020 Free Software Foundation, Inc.
;;
;; Author: Carsten Dominik <carsten at orgmode dot org>
;; Maintainer: Bastien Guerry <bzg@gnu.org>
;; Keywords: outlines, hypermedia, calendar, wp
;; Homepage: https://orgmode.org
;; Version: 9.3.6
;;
;; This file is part of GNU Emacs.
```

So here ut says that it is version 9.3.6. However if you've written a number yourself I'm not sure. My guess is that something is wrong with your org installation (older version) or you have some kind of preview version of org-mode 9.4 or similar, and maybe they've changed `org-get-heading` there.

**Comment by michaelsjackson** [comment]
I downloaded from https://orgmode.org/
this link: https://orgmode.org/org-latest.tar.gz
where it says: Daily snapshots of the development version: tar.gz 

I guess, even this is not true, when looking at the date with 2016 :baby_chick: 

If org-mode website is not trustable, how can its code then be?  :dancers: 

This is my head part:

> ;;; org.el --- Outline-based notes management and organizer -*- lexical-binding: t; -*-
> 
> ;; Carstens outline-mode for keeping track of everything.
> ;; Copyright (C) 2004-2016 Free Software Foundation, Inc.
> ;;
> ;; Author: Carsten Dominik <carsten at orgmode dot org>
> ;; Maintainer: Carsten Dominik <carsten at orgmode dot org>
> ;; Keywords: outlines, hypermedia, calendar, wp
> ;; Homepage: http://orgmode.org
> ;;
> ;; This file is part of GNU Emacs.
> ;;
> ;; GNU Emacs is free software: you can redistribute it and/or modify
> ;; it under the terms of the GNU General Public License as published by
> ;; the Free Software Foundation, either version 3 of the License, or
> ;; (at your option) any later version.
> 
> ;; GNU Emacs is distributed in the hope that it will be useful,
> ;; but WITHOUT ANY WARRANTY; without even the implied warranty of
> ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> ;; GNU General Public License for more details.
> 
> ;; You should have received a copy of the GNU General Public License
> ;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.
> ;;
> ;;; Commentary:
> ;;
> ;; Org is a mode for keeping notes, maintaining ToDo lists, and doing
> ;; project planning with a fast and effective plain-text system.
> ;;
> ;; Org mode develops organizational tasks around NOTES files that
> ;; contain information about projects as plain text.  Org mode is
> ;; implemented on top of outline-mode, which makes it possible to keep
> ;; the content of large files well structured.  Visibility cycling and
> ;; structure editing help to work with the tree.  Tables are easily
> ;; created with a built-in table editor.  Org mode supports ToDo
> ;; items, deadlines, time stamps, and scheduling.  It dynamically
> ;; compiles entries into an agenda that utilizes and smoothly
> ;; integrates much of the Emacs calendar and diary.  Plain text
> ;; URL-like links connect to websites, emails, Usenet messages, BBDB
> ;; entries, and any files related to the projects.  For printing and
> ;; sharing of notes, an Org file can be exported as a structured ASCII
> ;; file, as HTML, or (todo and agenda items only) as an iCalendar
> ;; file.  It can also serve as a publishing tool for a set of linked
> ;; webpages.
> ;;
> ;; Installation and Activation
> ;; ---------------------------
> ;; See the corresponding sections in the manual at
> ;;
> ;;   http://orgmode.org/org.html#Installation
> ;;
> ;; Documentation
> ;; -------------
> ;; The documentation of Org mode can be found in the TeXInfo file.  The
> ;; distribution also contains a PDF version of it.  At the homepage of
> ;; Org mode, you can read the same text online as HTML.  There is also an
> ;; excellent reference card made by Philip Rooke.  This card can be found
> ;; in the doc/ directory.
> ;;
> ;; A list of recent changes can be found at
> ;; http://orgmode.org/Changes.html
> ;;
> ;;; Code:
>

**Comment by michaelsjackson** [comment]
Now, will try this: https://orgmode.org/org-9.3.6.tar.gz

**Comment by michaelsjackson** [comment]
Ok, yankpad working again with this.

However, bash results are not added into org-mode, which works from terminal but not as org-babel within org-mode, ok, this is another topic, also not related to yankpad at all.  Just another org-mode problem, which was working in the past.  Even evince not starting after latex to pdf export.  Two simple things, but I am using those permanently, not sure why they do not work, hmm.  Have to investigate more.  Not fun, for sure.

Thanks for your caring and comment above, I guess I can close this here again.
