### ISSUE TITLE
Support '<' in keyword

### ISSUE THREAD

**Issue by yuchen-lea** [Kungsgeten/yankpad#67]
Thanks for this great work, helps a lot ;D

It seems "<" is not fully supported now. For example, I have a snippet:

> ** <s-py: python3                                              :props:
> #+BEGIN_SRC python :python "python3" :results output
> $0
> #+END_SRC

What I expect for expanding`<s-py` would be:

> #+BEGIN_SRC python :python "python3" :results output
> $0
> #+END_SRC

However, it's:

> <#+BEGIN_SRC python :python "python3" :results output
> $0
> #+END_SRC

It seems `<s-py` is identified as the keyword during expanding but only `s-py`is replaced.

------------------
yankpad Version: 2.30
GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, Carbon Version 162 AppKit 1894.3) of 2020-05-28
Org mode version 9.3.6

**Comment by Kungsgeten** [comment]
Hi! Sorry for the very late response. `yankpad` use `symbol-at-point` to check the word before point when matching the keyword. `symbol-at-point` doesn't pickup some characters unfortunately. I'm not quite sure how to fix that, but maybe another type of "X-at-point" function could be used, or written.

**Comment by nettoyoussef** [comment]
The solution posted by @yuchen-lea is great but only works for symbols at the beginning of tags, such as <s-py.

I improved it to work also for symbols at the end, such as lr(, lr{, lr[ etc.

```lisp
(defun keyword-with-bound-at-point ()
  "Get current keyword and its bound.
which is from current point to back to first empty char."
  (interactive)
  (save-excursion
    (let
      (beg (end (point)))
      (if
          (re-search-forward "[[:space:]]" nil t -1)
          (setq beg (+ (point) 1))
      )
      (goto-char end)
      (if
          (re-search-forward "[[:space:]]" nil t +1)
          (setq end (- (point) 1))
      )
      (cons (buffer-substring beg end) (cons beg end))
    )
  )
)

```

**Comment by yuchen-lea** [comment]
@nettoyoussef  Oh,thanks to your imrovement! However, it seems the solution also works for keywords with symbols at the end, like `lr(` . Since the keyword is **from current point to last non-blank char**, it should be fine as long as the ending char is not blank.

**Comment by nettoyoussef** [comment]
Hi @yuchen-lea, thanks again for your snippet! 

Not sure if I understood you. On my config, your solution only works for symbols at the beginning.
That makes sense because the function `re-search-forward` has a `-1` argument, which makes it search
word boundaries backward (so from the current point to the first non-blank char, it does the opposite with a positive argument). 

So the snippet gets the boundaries including only up to the first symbol with no spaces. 
That is why I included the second search updating `end`.

But I am no lisp expert.

**Comment by Kungsgeten** [comment]
Thanks @yuchen-lea for the PR #73 which fixed this.
