### ISSUE TITLE
Multi level selection within same category, example :s:s:

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/yankpad#69]
Just had following idea, I guess this is not possible yet, but I could be wrong, due to not knowing all features of yankpad.

We are in one specific category, now let us assume we have quite many entries there, thus the selection list below gets a bit too big, one way of interesting filtering technique could be allowing multi level selections. 

Example:  If my tag would be :s:s:
Those entries should not be displayed in the list below, but only after the first hitting of s. A second hitting of s would trigger it.  So I could have another entry like :s:t:     which would be displayed after first s, triggered after following t.

Difference to current implementation, instead of considering only the last single tag, it would consider the last two, or three tags, if they are single letter (could be used to define a multi level entry or not)

Not sure if useful or easy to implement or if it makes sense also to you?

Right now I would need to define multiple categories to achieve a similar workflow, but being able to branch within same category could be also useful I guess.

Anyway, for now I will stick to category selection, not really necessary overcomplicating things.  Thought will share the idea here quickly. Have a nice day.

**Comment by Kungsgeten** [comment]
Hi!

I haven't tested it, but if I understand correctly I think this should work if you set the last tag to `ss`. Please try and see. In that case you could have `ss` for one tag and `st` for another.

**Comment by Kungsgeten** [comment]
I tried the solution I posted, and it worked. I haven't heard back from the origina poster in a while, so I'm closing this.
