### ISSUE TITLE
how does one insert orgmode snippets that contain * ?

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#7]
Hi again

i was wondering how using yankpad one would insert snippets that have org headers in them (ie ***). in yas its not a problem ie to have a snippet like this

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: projfile
# key: projfile
# binding: direct-keybinding
# --
** P0XX.$1
*** Aims
*** related papers
*** manuscript
*** work
**** data
**** model
*** results

```

yet in yankspad due to the fact that the snippets them selves are org mode headers/content this above snippet messes up things.
anyway around this?

best

z

**Comment by Kungsgeten** [comment]
You can try indenting the whole snippet one space (mark the whole snippet and use `M-x indent-rigidly`). I believe this will work as long as you do not have lines with only one star, because then org-mode will convert it into a list. I should probably look into this...

**Comment by Kungsgeten** [comment]
I'm not quite sure on how to fix this. The snippet could be inserted as raw data, but then the snippet would have to be indented (and the indentation will be inserted too).

**Comment by zeltak** [comment]
hmmm just a wild thought. perhaps the use of orgmode code blocks/ babel can help here?
for example for snippets with problematic characters such as * etc we could put that inside orgmode example blocks
```
#+BEGIN_EXAMPLE
* snip
#+END_EXAMPLE
```
would that help at all?

best

Z

**Comment by Kungsgeten** [comment]
It could work, but I think it would require the use of the `flet` function (or be really cumbersome to code), which is deprecated in Emacs lisp.

**Comment by Kungsgeten** [comment]
Okay, so I've submitted a solution: `\*` at the beginning of a line will be replaced by `\*`. So in your example:
```
\** P0XX.$1
\*** Aims
\*** related papers
\*** manuscript
\*** work
\**** data
\**** model
\*** results
```

**Comment by zeltak** [comment]
just to be clear this will insert the `\*` not just `*` so one still needs to go and delete the `\` right?

thx

Z

**Comment by Kungsgeten** [comment]
No, \* at the beginning of a line (column 0) should insert * and nothing
else.
