### ISSUE TITLE
yankpad--trigger-snippet-function: First block in snippet must be an org-mode src block

### ISSUE THREAD

**Issue by snowman** [Kungsgeten/yankpad#74]
Example yankpad file:

```org
* Category 1
** elfeed                                            :func:e:

```

when calling with `M-x yankpad-insert RET elfeed` or `M-x yankpad-map RET e`, it throws error:

> yankpad--trigger-snippet-function: First block in snippet must be an org-mode src block

**Comment by snowman** [comment]
Okay, I found it.

When calling with function `(defun yankpad--trigger-snippet-function (snippetname content)` the arguments are:
- `snippetname`: `"elfeed"`
- `content`: `"\n"`

So the `content` should be trim whitespaces first or do not add newline(s) inside `** elfeed   :func:e` heading.

**Comment by Kungsgeten** [comment]
Thanks! Should be fixed now.
