### ISSUE TITLE
Yankpad show repeated snippets

### ISSUE THREAD

**Issue by Randy1Burrell** [Kungsgeten/yankpad#77]
This is a really handy package for org-mode users. However, whenever I invoke the function yankpad-insert I see repetitions of the snippets I currently have for the mode I am in. 

Notice in the picture of the options that gets displayed are repeated options.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10135939/104042992-2959b580-51a9-11eb-9126-95bb9616c5f2.png">

Here is my Yankpad configuration:

```emacs-lisp
(use-package yankpad
  :config
  (bind-key "<f9>" 'yankpad-map)
  (bind-key "<f12>" 'yankpad-expand)
  (bind-key "C-c s" 'yankpad-insert))
```
Though it's not a critical bug, it's annoying and any solution would be appreciated.

**Comment by Kungsgeten** [comment]
Hi! Happy to hear that you enjoy the package. Could you post your yankpad-file? I haven't had this problem myself.

**Comment by Randy1Burrell** [comment]
Yeah mon (**_*Jamaican Voice*_**) nice work. The problem seems to have mysteriously disappeared after deleting two of the three snippets I had.

Here's what my yankpad.org file looked like:
```org
* emacs-lisp-mode
** use-package
(use-package $0)
** function
(defun $0)
** package-install
(unless (package-installed-p '${0})
   (package-install '$0))
```

While I have you here, there is another small query that you might be able to help me with. Are there anyway to do mirroring in the snippets. yasnippet has this feature, but I haven't been able to get it to work in Yankpad. An example of what I was trying is in the package-install snippet above.

**Comment by Randy1Burrell** [comment]
The bug has returned. After using Yankpad for the past few days I have found that this bug occurs when I have snippets for multiple modes.

Here's my current Yankpad file:

* emacs-lisp-mode
** use-package
(use-package $0)
** function
(defun $0)

* org-mode
** Weekly Planning
\\*** Last weeks big 3
\\***** How far did you get [%]$7
\****** [$2] $1
\\****** [$4] $3
\\****** [$6] $5
\\***** What worked?
\\****** $8
\\***** What didn't work?
\\****** $9
\\***** What will you keep doing?
\\****** $10
\\***** What will you improve?
\\****** $11
\\***** What will you start doing?
\\****** $12
\\***** What will you stop doing?
\\****** $13
\\**** Review tasks and actions [/]$17
\\***** [$14] DEFERRED TASKS
\\***** [$15] DELEGATED TASKS
\\***** [$16] REVIEW DAILY NOTES
\\**** Important updates, deadlines and task this week [/]$24
\\***** [$19] Personal
      1. $18
\\***** [$21] Professional
      1. $20
\\***** [$23] Learning
      1. $22
\\**** Big 3
\\***** $25



snippets when in emacs-lisp-mode
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10135939/104116533-67f58a00-52e7-11eb-93d5-180912c1ff83.png">

snippets when in org-mode
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10135939/104116565-a12dfa00-52e7-11eb-8410-13cc82d02b81.png">

**Comment by AloisJanicek** [comment]
This has to be related to `ivy` because when you disable `ivy-mode`, `yankpad` items in `emacs`' built-in `completion-read` interface aren't doubled as they are in `ivy` interface.

I verified this on emacs 28 with heavily customized doom, on emacs 27 with vanilla doom and also on vanilla emacs 27 config.

**Comment by Kungsgeten** [comment]
@AloisJanicek Thanks you for bug searching!

**Comment by Kungsgeten** [comment]
The bug was introduced in #75, but should be fixed now. Sorry for not noticing earlier @Randy1Burrell, I hadn't pulled the Github version into my local branch.
