### ISSUE TITLE
Result of :results: snippet is wrapped with quotes

### ISSUE THREAD

**Issue by stefan2904** [Kungsgeten/yankpad#79]
I am currently trying to create a snippet that insert the result of a bash script using the amazing `:results:` magic-tag. Unfortuantly the result is not inserted as it is, but instead wrapped in quotation marks:

---

For testing, I have a snippet that looks like this:

```org
** time: Insert current time  :results:

#+begin_src bash :results output
date +%H:%M
#+end_src
```

When I expand the snippet: 

### Expected result:

```
20:31
```

### Actual result:

```
"20:31
"
```

---

Is this a bug, am I doing something wrong, or is there another reason for this behavior?

Thanks a lot!

**Comment by Kungsgeten** [comment]
Hi! I haven't used `:results:` much myself, but there seems to be an issue when the result returned from the block was a string. The string then got "converted into a string", which added the quotation marks. This should be fixed by the latest commit. In your specific example, if you don't want the linebreak, you could omit the `:results output` from the src block header.

**Comment by stefan2904** [comment]
Thanks a lot Erik! It works now!

---

For future reference, the following works:

### Yankpad

For the bash snippets, I removed the ` :results output` flag as suggested [above](https://github.com/Kungsgeten/yankpad/issues/79#issuecomment-868835984). For the python snipped that did not work (as `:results value` is the default , resulting in `None`).

```org
** time: current time :results:

#+begin_src bash 
date +%H:%M
#+end_src


** date: Insert today's date :results:

#+begin_src bash
date --iso-8601
#+end_src


** pythontest: Test Test :results:

#+begin_src python :results output
  print('hello world')
#+end_src
```

### output

time:
```
14:19
```

date:
```
2021-06-28
```

pythontest:
```
hello world

```
