### ISSUE TITLE
another hook request, change to catagory per file name?

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#8]
Hi again (last issue for the day..promise ;-))

i see you added a change category based on projectile find file. i though it could also be cool to add another change category hook based on file name. so for example when i change to my cooking.org file, the category will change to "cooking"
not a big must just thought it could be cool and make the snippet search cleaner
best

Z

**Comment by Kungsgeten** [comment]
I agree that it would be a nice feature. You can try adding this as the first line in your file (haven't tried it, but should work):

`-*- yankpad-category: category_name -*-`

See [this link](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables) for more information about file specific variables.

**Comment by zeltak** [comment]
thx! this would be ideal bit i dont think it currently works (using latest from melpa..maybe you havent pushed to melpa yet?)

i have 
```-*- yankpad-category: food -*-```
and a category named food in my yankpad file. when i try to insert a snippet the list comes empty again

best
Z

**Comment by Kungsgeten** [comment]
Try this instead:

`-*- yankpad-category: "food"; -*-`

Emacs will warn you about it not being safe to set the variable. I will push an update fixing this.

**Comment by zeltak** [comment]
amazing! this works flawlessly

man i really love yankpad, the best new package for emacs ive discovered in quite a while, also the cool yas integration is also great with the $1 etc..
thx so much for all your hard work, its truly great :)

Z

**Comment by Kungsgeten** [comment]
You're welcome! Glad you like it, please spread the word :)
