### ISSUE TITLE
Regression: using yankpad-expand on a keyword at beginning of file does not expand!

### ISSUE THREAD

**Issue by ag91** [Kungsgeten/yankpad#83]
Hi, thanks for this package once more!

I have noticed that after the last update I cannot expand snippets at beginning of file anymore.
The bug was definitely introduced after [this commit](https://github.com/Kungsgeten/yankpad/commit/eb99dac81f6f53a293215e8a0ef3707a45f86f96), because I reverted to that and things work again.
Probably https://github.com/Kungsgeten/yankpad/pull/81 is related but does not solve my issue (I tried to use that code).

You should be able to reproduce by simply creating a file, adding the keyword of your snippet and trying to expand it: nothing will happen with the latest version of yankpad!

Thanks again!

**Comment by isamert** [comment]
Hey @ag91, I also realized #81 was failing to fix the issue in every case, I pushed a new commit to fix the issue. Can you check it again?

**Comment by ag91** [comment]
Yeah, your `bol` change works for me. Thanks for the time you put into this, I will use your version until this gets merged

**Comment by Kungsgeten** [comment]
Fixed by #81, thanks!
